source 'https://rubygems.org'

gem 'rack', '<2.0'
gem 'sqlite3'
gem 'sinatra'
gem 'sinatra-namespace'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'erubis'
gem 'bcrypt'
gem 'thin'
gem 'pony'
